### ISSUE TITLE
Blinking LED not compiling on Kubuntu 14.04, Arduino IDE 1.6.7

### ISSUE THREAD

**Issue by pkout** [pololu/a-star-32u4-arduino-library#2]
Hi, 

I installed this library using Arduino IDE 1.6.7's library manager. The installation seemed to go without a problem. However, when I selected my board to "Arduino/Geniuino Uno" and picked the port /dev/ttyACM0 and then hit the Verify button in Arduino IDE, I got the following error (I am on Kubuntu 14.04). Any idea what's missing? Thanks.

Arduino: 1.6.7 (Linux), Board: "Arduino/Genuino Uno"

/media/Data/Projects/Hardware/arduino/arduino-1.6.7/arduino-builder -dump-prefs -logger=machine -hardware "/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware" -tools "/media/Data/Projects/Hardware/arduino/arduino-1.6.7/tools-builder" -tools "/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/tools/avr" -built-in-libraries "/media/Data/Projects/Hardware/arduino/arduino-1.6.7/libraries" -libraries "/home/petr/Arduino/libraries" -fqbn=arduino:avr:uno -ide-version=10607 -build-path "/tmp/build46f886b097cb010b348915c677b98a00.tmp" -warnings=default -prefs=build.warn_data_percentage=75 -verbose "/home/petr/Arduino/libraries/AStar32U4/examples/BlinkLEDs/BlinkLEDs.ino"
/media/Data/Projects/Hardware/arduino/arduino-1.6.7/arduino-builder -compile -logger=machine -hardware "/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware" -tools "/media/Data/Projects/Hardware/arduino/arduino-1.6.7/tools-builder" -tools "/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/tools/avr" -built-in-libraries "/media/Data/Projects/Hardware/arduino/arduino-1.6.7/libraries" -libraries "/home/petr/Arduino/libraries" -fqbn=arduino:avr:uno -ide-version=10607 -build-path "/tmp/build46f886b097cb010b348915c677b98a00.tmp" -warnings=default -prefs=build.warn_data_percentage=75 -verbose "/home/petr/Arduino/libraries/AStar32U4/examples/BlinkLEDs/BlinkLEDs.ino"
"/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/arduino/avr/cores/arduino" "-I/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/arduino/avr/variants/standard" "/tmp/build46f886b097cb010b348915c677b98a00.tmp/sketch/BlinkLEDs.ino.cpp" -o "/dev/null"
"/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/arduino/avr/cores/arduino" "-I/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/arduino/avr/variants/standard" "-I/home/petr/Arduino/libraries/AStar32U4" "/tmp/build46f886b097cb010b348915c677b98a00.tmp/sketch/BlinkLEDs.ino.cpp" -o "/dev/null"
"/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/arduino/avr/cores/arduino" "-I/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/arduino/avr/variants/standard" "-I/home/petr/Arduino/libraries/AStar32U4" "/home/petr/Arduino/libraries/AStar32U4/AStar32U4.cpp" -o "/dev/null"
"/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/arduino/avr/cores/arduino" "-I/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/arduino/avr/variants/standard" "-I/home/petr/Arduino/libraries/AStar32U4" "/home/petr/Arduino/libraries/AStar32U4/AStar32U4Motors.cpp" -o "/dev/null"
"/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/arduino/avr/cores/arduino" "-I/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/arduino/avr/variants/standard" "-I/home/petr/Arduino/libraries/AStar32U4" "/home/petr/Arduino/libraries/AStar32U4/PololuBuzzer.cpp" -o "/dev/null"
"/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/arduino/avr/cores/arduino" "-I/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/arduino/avr/variants/standard" "-I/home/petr/Arduino/libraries/AStar32U4" "/home/petr/Arduino/libraries/AStar32U4/PololuHD44780.cpp" -o "/dev/null"
"/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/arduino/avr/cores/arduino" "-I/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/arduino/avr/variants/standard" "-I/home/petr/Arduino/libraries/AStar32U4" "/home/petr/Arduino/libraries/AStar32U4/Pushbutton.cpp" -o "/dev/null"
"/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/arduino/avr/cores/arduino" "-I/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/arduino/avr/variants/standard" "-I/home/petr/Arduino/libraries/AStar32U4" "/tmp/build46f886b097cb010b348915c677b98a00.tmp/sketch/BlinkLEDs.ino.cpp" -o "/dev/null"
"/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/arduino/avr/cores/arduino" "-I/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/arduino/avr/variants/standard" "-I/home/petr/Arduino/libraries/AStar32U4" "/tmp/build46f886b097cb010b348915c677b98a00.tmp/sketch/BlinkLEDs.ino.cpp" -o "/tmp/build46f886b097cb010b348915c677b98a00.tmp/preproc/ctags_target_for_gcc_minus_e.cpp"
"/media/Data/Projects/Hardware/arduino/arduino-1.6.7/tools-builder/ctags/5.8-arduino5/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "/tmp/build46f886b097cb010b348915c677b98a00.tmp/preproc/ctags_target_for_gcc_minus_e.cpp"
"/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/tools/avr/bin/avr-g++" -c -g -Os  -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/arduino/avr/cores/arduino" "-I/media/Data/Projects/Hardware/arduino/arduino-1.6.7/hardware/arduino/avr/variants/standard" "-I/home/petr/Arduino/libraries/AStar32U4" "/tmp/build46f886b097cb010b348915c677b98a00.tmp/sketch/BlinkLEDs.ino.cpp" -o "/tmp/build46f886b097cb010b348915c677b98a00.tmp/sketch/BlinkLEDs.ino.cpp.o"
In file included from /home/petr/Arduino/libraries/AStar32U4/AStar32U4LCD.h:9:0,
                 from /home/petr/Arduino/libraries/AStar32U4/AStar32U4.h:13,
                 from /home/petr/Arduino/libraries/AStar32U4/examples/BlinkLEDs/BlinkLEDs.ino:4:
/home/petr/Arduino/libraries/AStar32U4/USBPause.h: In constructor 'USBPause::USBPause()':
/home/petr/Arduino/libraries/AStar32U4/USBPause.h:44:22: error: 'UDIEN' was not declared in this scope
         savedUDIEN = UDIEN;
                      ^
/home/petr/Arduino/libraries/AStar32U4/USBPause.h:48:22: error: 'UENUM' was not declared in this scope
         savedUENUM = UENUM;
                      ^
/home/petr/Arduino/libraries/AStar32U4/USBPause.h:52:24: error: 'UEIENX' was not declared in this scope
         savedUEIENX0 = UEIENX;
                        ^
/home/petr/Arduino/libraries/AStar32U4/USBPause.h: In destructor 'USBPause::~USBPause()':
/home/petr/Arduino/libraries/AStar32U4/USBPause.h:59:9: error: 'UENUM' was not declared in this scope
         UENUM = 0;
         ^
/home/petr/Arduino/libraries/AStar32U4/USBPause.h:60:9: error: 'UEIENX' was not declared in this scope
         UEIENX = savedUEIENX0;
         ^
/home/petr/Arduino/libraries/AStar32U4/USBPause.h:66:9: error: 'UDIEN' was not declared in this scope
         UDIEN = savedUDIEN;
         ^
In file included from /home/petr/Arduino/libraries/AStar32U4/examples/BlinkLEDs/BlinkLEDs.ino:4:0:
/home/petr/Arduino/libraries/AStar32U4/AStar32U4.h: In function 'bool usbPowerPresent()':
/home/petr/Arduino/libraries/AStar32U4/AStar32U4.h:62:12: error: 'USBSTA' was not declared in this scope
     return USBSTA >> VBUS & 1;
            ^
/home/petr/Arduino/libraries/AStar32U4/AStar32U4.h:62:22: error: 'VBUS' was not declared in this scope
     return USBSTA >> VBUS & 1;
                      ^
Using library AStar32U4 at version 1.0.3 in folder: /home/petr/Arduino/libraries/AStar32U4 
exit status 1
Error compiling.

**Comment by pkout** [comment]
Ah, I got it. I have to set the Board to Arduino Leonardo. Now i am getting another error. When I try to upload the compiled code to the board, I get the error message: 

Arduino: 1.6.7 (Linux), Board: "Arduino Leonardo"

Sketch uses 6,058 bytes (21%) of program storage space. Maximum is 28,672 bytes.
Global variables use 191 bytes (7%) of dynamic memory, leaving 2,369 bytes for local variables. Maximum is 2,560 bytes.
avrdude: butterfly_recv(): programmer is not responding
Problem uploading to board.  See http://www.arduino.cc/en/Guide/Troubleshooting#upload for suggestions.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

Do I need special drivers for Ubuntu to make this work? Thanks! It does work on Windows 8.

**Comment by DavidEGrayson** [comment]
Hello.  We use GitHub issues to discuss bugs and feature requests related to the library.  You are having trouble uploading to your board, which is not a library issue, so I will close this issue.

You didn't say what hardware you have, but if you have an A-Star 32U4, then I suggest reading the [A-Star 32U4 User's Guide](https://www.pololu.com/docs/0J61) and then contacting [Pololu support](https://www.pololu.com/support) if you are still having trouble.
