### ISSUE TITLE
20 kHz PWM frequency generates noise

### ISSUE THREAD

**Issue by 3sigma** [pololu/a-star-32u4-arduino-library#3]
Hello,

I'm using an "[A-Star 32U4 Robot Controller LV with Raspberry Pi Bridge](https://www.pololu.com/product/3117)" with a [DC Motor with encoder](https://www.pololu.com/product/2284) with a speed control program.
It appears that the 20 kHz PWM frequency generates a lot of noise, especially at low speed. I tried with a prescaler equal to 8 (TCCR1B = 0b00010010, which corresponds to 2.5 kHz), it is far better.
Is there a specific reason why this frequency (20 kHz) is used ? Of course, 2.5 kHz is not ultrasonic and in theory you can here the PWM, but in fact the motor is louder and you almost don't hear the PWM.

Thanks,

Nicolas

**Comment by ryantm** [comment]
Hi, Nicolas.

We chose 20 kHz PWM frequency based on it being ultrasonic, and it subjectively seemed good to us when a couple of us tested some of our gearmotors at different frequencies. It is surprising that you are getting worse noise at 20 kHz compared with 2.5 kHz. Can you share your sketch code and a schematic with details of your connections, motors, and power supply? A video of your setup at the two different frequencies would also be appreciated!

Ryan
